default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.10
    hooks:
      - id: dbt-parse
        additional_dependencies: ['dbt-core', 'dbt-duckdb']
      # - id: dbt-docs-generate
      - id: check-model-has-properties-file
        files: ^models/
      - id: check-script-semicolon
      - id: check-script-has-no-table-name
        files: ^models/
      - id: check-model-has-all-columns
        files: ^models/
      - id: check-model-columns-have-desc
      - id: check-model-has-tests
        args: ["--test-cnt", "8", "--"]
        files: ^models/staging
      - id: check-model-has-tests
        args: ["--test-cnt", "4", "--"]
        files: ^models/(intermediate|marts)
      - id: check-model-parents-name-prefix
        args: ["--whitelist", "stg_", "--"]
      - id: check-model-has-description
        files: ^models/
      - id: check-source-has-tests
        args: ["--test-cnt", "8", "--"]
      - id: check-source-has-tests-by-type
        args: ["--tests", "schema=1", "--"]
      - id: check-source-has-freshness
        args: ["--freshness", "error_after", "warn_after", "--"]
        files: ^models/
      - id: check-source-columns-have-desc
      - id: check-source-has-description
      - id: check-source-table-has-description
      - id: check-macro-has-description
