[pytest]
pythonpath = .
testpaths = src/tests
addopts = --html=src/tests/test-logs/testreport.html
    --self-contained-html
    --junitxml=src/tests/test-logs/testreport.xml
    -ra -vv -q
    --tb=short
filterwarnings =
    ignore::DeprecationWarning
