[tox]
envlist = py{313}-{dbt,orchestration,prefect-adhoc-command,adhocsql,unittests,lint}
no_package = true
requires = 
    tox-uv

[base]
deps = pyarrow
       polars

[dbt]
deps = dbt-core
       duckdb
       dbt-duckdb
       sqlfluff

[prefectdbt]
deps = prefect
       pydantic
       typer
       prefect-dbt

[myenv]
deps = pytest
       coverage
       pytest-html

[lint]
deps = pre-commit

[testenv]
platform = dbt: linux
           orchestration: linux
           adhocsql: linux
           prefect-adhoc-command: linux
           unittests: linux
           lint: linux
setenv =
    DBT_SEND_ANONYMOUS_USAGE_STATS=False
    DBT_PROFILES_DIR=.
passenv = *
allowlist_externals =
    bash
deps =
    dbt: {[base]deps}
    dbt: {[dbt]deps}
    adhocsql: {[base]deps}
    adhocsql: {[dbt]deps}
    orchestration: {[dbt]deps}
    orchestration: {[prefectdbt]deps}
    prefect-adhoc-command: {[dbt]deps}
    prefect-adhoc-command: {[prefectdbt]deps}
    unittests: {[dbt]deps}
    unittests: {[prefectdbt]deps}
    unittests: {[myenv]deps}
    lint: {[dbt]deps}
    lint: {[lint]deps}
description =
    dbt: execute adhoc dbc command
    orchestration: run development tasks for the prefect-dbt feature
    adhocsql: run adhoc .sql script with DuckDB
    prefect-adhoc-command: run adhoc Prefect command
    unittests: run unit tests on Prefect flows and tasks
    lint: run code checks for the linting feature
commands =
    dbt: dbt {posargs}
    orchestration: python3 dbt_orchestrator.py --commands {posargs}
    prefect-adhoc-command: prefect {posargs}
    adhocsql: python run_sql_query.py {posargs}
    unittests: coverage run -m pytest
    unittests: coverage report -m
    unittests: coverage html
    unittests: coverage xml
    lint: dbt deps
    lint: dbt parse
    lint: pre-commit autoupdate
    lint: pre-commit install
    lint: pre-commit run -v --all-files --show-diff-on-failure {posargs}
