name: Deploy dbt Docs to GitHub Pages

on:
  workflow_run:
    workflows: ["CI"]
    types: [com pleted]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      # Forces dbt to look in repo root directory for profiles.yml
      DBT_PROFILES_DIR: .
      SNOWFLAKE_ACCOUNT_LOCATION: ${{ secrets.SNOWFLAKE_LOCATION }}
      SNOWFLAKE_USER_NAME: ${{ secrets.SNOWFLAKE_USER_NAME }}
      SNOWFLAKE_USER_PASSWORD: ${{ secrets.SNOWFLAKE_USER_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: v0.81.0
          manifest-path: pyproject.toml
          run-install: true

      - name: Generate dbt Docs
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          pixi run prefect-dbt "debug"
          pixi run prefect-dbt "deps"
          pixi run prefect-dbt "run"
          pixi run prefect-dbt "test"
          pixi run prefect-dbt "docs generate --no-compile"

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./target"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
