[tox]
envlist = py{313}-{dbt,orchestration,adhocsql,lint,website}
no_package = true

[base]
deps = pyarrow==25.0.1
       polars==1.44.2

[dbt]
deps = dbt-core==1.12.5
       duckdb==1.5.5
       dbt-duckdb==1.11.0
       sqlfluff==4.3.0

[prefectdbt]
deps = prefect==3.8.6
       pydantic==2.13.5
       typer==0.27.2
       prefect-dbt==0.7.25

[lint]
deps = pre-commit==4.6.2

[testenv]
platform = dbt: linux
           orchestration: linux
           adhocsql: linux
           lint: linux
           website: linux
setenv =
    DBT_SEND_ANONYMOUS_USAGE_STATS=False
passenv = *
allowlist_externals =
    bash
    quarto
dependency_groups =
    base
    dbt: dbt
    adhocsql: dbt
    orchestration: dbt
    orchestration: prefectdbt
    lint: dbt
    lint: lint
description =
    dbt: execute adhoc dbc command
    orchestration: run development tasks for the prefect-dbt feature
    adhocsql: run adhoc .sql script with DuckDB
    lint: run code checks for the linting feature
    quarto: run Quarto commands for documentation
commands =
    dbt: dbt {posargs}
    orchestration: python3 dbt_orchestrator.py --commands {posargs}
    adhocsql: python run_sql_query.py {posargs}
    lint: dbt deps
    lint: dbt parse
    lint: pre-commit autoupdate
    lint: pre-commit install
    lint: pre-commit run -v --all-files --show-diff-on-failure {posargs}
    website: quarto {posargs}
