[tox]
envlist = py{313}-{dbt,orchestration,adhocsql,unittests,lint}
no_package = true
requires = 
    tox-uv

[testenv]
platform = dbt: linux
           orchestration: linux
           adhocsql: linux
           unittests: linux
           lint: linux
setenv =
    DBT_SEND_ANONYMOUS_USAGE_STATS=False
passenv = *
base_python_file = .python-version
runner = uv-venv-lock-runner
allowlist_externals =
    bash
dependency_groups =
    dbt
    dbt: base
    adhocsql: base
    orchestration: prefectdbt
    unittests: prefectdbt
    unittests: myenv
    lint: lint
description =
    dbt: execute adhoc dbc command
    orchestration: run development tasks for the prefect-dbt feature
    adhocsql: run adhoc .sql script with DuckDB
    unittests: run unit tests on Prefect flows and tasks
    lint: run code checks for the linting feature
commands =
    dbt: dbt {posargs}
    orchestration: python3 dbt_orchestrator.py --commands {posargs}
    adhocsql: python run_sql_query.py {posargs}
    unittests: coverage run -m pytest
    unittests: coverage report -m
    unittests: coverage html
    unittests: coverage xml
    lint: dbt deps
    lint: dbt parse
    lint: pre-commit autoupdate
    lint: pre-commit install
    lint: pre-commit run -v --all-files --show-diff-on-failure {posargs}
